import { dictionaries, type Dictionary } from "../dictionaries";
import type { Locale } from "./locales";

/**
 * Resolves the copy for a locale.
 *
 * `en` and `hi` are hand-written in lib/dictionaries.ts and are returned as-is —
 * machine translation never overwrites copy a human wrote. Every other locale is
 * assembled in three layers, later winning over earlier:
 *
 *   1. the English dictionary        — guarantees no key is ever missing
 *   2. lib/i18n/generated/<code>.json — Bhashini output, regenerated by script
 *   3. lib/i18n/overrides/<code>.json — hand corrections, never auto-written
 *
 * A partly-translated locale therefore renders the translated strings and falls
 * back to English for the rest, rather than showing blanks.
 */

type Json = Record<string, unknown>;

function isPlainObject(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Deep-merges `patch` onto `base`. Arrays merge element-wise so a partially
 *  translated list keeps the English entries it has no translation for. */
function merge<T>(base: T, patch: unknown): T {
  if (patch === undefined || patch === null) return base;

  if (Array.isArray(base)) {
    if (!Array.isArray(patch)) return base;
    return base.map((item, i) =>
      i < patch.length ? merge(item, patch[i]) : item,
    ) as unknown as T;
  }

  if (isPlainObject(base)) {
    if (!isPlainObject(patch)) return base;
    const out: Json = { ...(base as Json) };
    for (const key of Object.keys(out)) {
      if (key in patch) out[key] = merge(out[key], patch[key]);
    }
    return out as T;
  }

  // Leaf: take the translation only if it is a non-empty string of the same type.
  if (typeof base === "string") {
    return (typeof patch === "string" && patch.trim() ? patch : base) as T;
  }
  return base;
}

// The generated/ and overrides/ barrels are rewritten by
// scripts/translate-bhashini.ts as locales are produced. Bundling them (rather
// than fetching at runtime) keeps the copy in the server-rendered HTML, which is
// what search engines and slow highway connections actually see.
import { loadGenerated, TRANSLATED } from "./generated";
import { loadOverrides } from "./overrides";

const cache = new Map<string, Dictionary>();

/**
 * The copy for a locale, if it is already available synchronously.
 *
 * `en` and `hi` always are — they are hand-written in lib/dictionaries.ts. Every
 * other locale lives in its own lazily-fetched chunk, so this returns English
 * until loadDictionary() has resolved it, and the built result thereafter. That
 * is the correct first paint: readable English rather than a flash of blanks.
 */
export function getDictionary(locale: Locale): Dictionary {
  if (locale === "en") return dictionaries.en;
  if (locale === "hi") return dictionaries.hi;
  return cache.get(locale) ?? dictionaries.en;
}

/** Fetches a locale's chunk and layers it over English. Cached, so switching
 *  back to a language already visited is instant. */
export async function loadDictionary(locale: Locale): Promise<Dictionary> {
  if (locale === "en") return dictionaries.en;
  if (locale === "hi") return dictionaries.hi;

  const hit = cache.get(locale);
  if (hit) return hit;

  const [generated, overrides] = await Promise.all([
    loadGenerated(locale),
    loadOverrides(locale),
  ]);
  const built = merge(merge(dictionaries.en, generated), overrides);
  cache.set(locale, built);
  return built;
}

export { merge as mergeDictionary };
export type { Dictionary };

/**
 * Whether a locale has copy of its own, as opposed to falling back to English.
 *
 * True for the two hand-written locales, and for any locale a translation run
 * has produced. The picker uses this to label the difference — without it, a
 * reader (or a developer) picks Tamil, sees English, and reasonably concludes
 * the language switcher is broken.
 */
export function isTranslated(locale: Locale): boolean {
  return locale === "en" || locale === "hi" || TRANSLATED.includes(locale);
}
