/**
 * Rewrites lib/i18n/generated/index.ts from whatever JSON files are present.
 * The Python backend calls this after writing its output, so the barrel is
 * generated by the same code path as the TypeScript backend's.
 */
import { writeBarrel } from "./lib/strings";

const present = writeBarrel();
console.log(
  present.length
    ? `Barrel updated — ${present.length} locale(s): ${present.join(", ")}`
    : "Barrel updated — no translated locales yet.",
);
